#!/bin/sh

# Add sudoers
#------------

/usr/sbin/addsudo /usr/bin/curl app-docker-core
/usr/sbin/addsudo /usr/bin/docker app-docker-core
/usr/sbin/addsudo /usr/bin/docker-compose app-docker-core
/usr/sbin/addsudo /usr/sbin/clearos-compose app-docker-core

# Disable subscription manager
#-----------------------------

CONFIGS=" search-disabled-repos.conf subscription-manager.conf product-id.conf"

for CONFIG in $CONFIGS; do
    CHECK=`grep ^enabled=1 "/etc/yum/pluginconf.d/$CONFIG" 2>/dev/null`
    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-docker - updating yum plugin: $CONFIG"
        sed -i -e 's/^enabled=1/^enabled=0/' "/etc/yum/pluginconf.d/$CONFIG"
    fi
done

# Disable Docker firewall integration
#------------------------------------

if [ -e /etc/sysconfig/docker-network ]; then
    CHECK=`grep "^DOCKER_NETWORK_OPTIONS=$" /etc/sysconfig/docker-network`
    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-docker - disabling iptables integration (init)"
        sed -i -e "s/^DOCKER_NETWORK_OPTIONS=$/DOCKER_NETWORK_OPTIONS='--iptables=false'/" /etc/sysconfig/docker-network

    else
        CHECK=`grep "^DOCKER_NETWORK_OPTIONS=.*iptables=false" /etc/sysconfig/docker-network`
        if [ -z "$CHECK" ]; then
            logger -p local6.notice -t installer "app-docker - disabling iptables integration"
            sed -i -e "s/^DOCKER_NETWORK_OPTIONS='/DOCKER_NETWORK_OPTIONS='--iptables=false /" /etc/sysconfig/docker-network
        fi
    fi
fi
